#CLient
CREATE TABLE client(
	id_client INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	first_name VARCHAR(100) NOT NULL, 
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;